### ISSUE TITLE
the folowings scripts aren't working for me

### ISSUE THREAD

**Issue by tebicap** [NatronGitHub/natron-python-scripting#1]
I'm in Kubuntu 19.04, Natron 2.3.14 portable

Channel
	🚫 autoAlpha
    No log.

Node Graph
	🚫 connectNodesList

    log in console:
Object::connect: No such signal GenericWatcher::taskFinished(int,WatcherCallerArgsPtr)
Object::connect: No such signal GenericWatcher::taskFinished(int,WatcherCallerArgsPtr)

    Script editor:
While executing script:
app = app1
connectNodesList()
Python error:
Python exception: local variable 'toNode' referenced before assignment
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/life/.Natron/Python_GUI/connectNodesList/connectNodesList.py", line 94, in connectNodesList
    if nodeToConnect.canConnectInput(0,toNode) == 1:
UnboundLocalError: local variable 'toNode' referenced before assignment

	🚫 openLocation
    Script editor:
While executing script:
app = app1
openLocation()
Python error:
Python exception: [Errno 2] No existe el archivo o el directorio
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/life/.Natron/Python_GUI/openLocation/openLocation.py", line 40, in openLocation
    subprocess.Popen( ['thunar', myFolder] , stdin = subprocess.PIPE, stdout = subprocess.PIPE)
  File "/home/life/Natron-2.3.14-Linux-x86_64bit/lib/python27.zip/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/life/Natron-2.3.14-Linux-x86_64bit/lib/python27.zip/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No existe el archivo o el directorio

Render
	🚫 flipbook (Renders but not open the viewer)
    Script editor:
While executing script:
app = app1
flipbook()()
Python error:
Python exception: (2, 'No existe el archivo o el directorio', '/usr/local/mrViewer-v5.1.1-Linux-64/bin/\n')
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/life/.Natron/Python_GUI/flipbook/flipbook.py", line 300, in flipbook
    os.chdir(viewerPath)
OSError: (2, 'No existe el archivo o el directorio', '/usr/local/mrViewer-v5.1.1-Linux-64/bin/\n')

Utils
	🚫 collectFiles
    Script editor:
While executing script:
app = app1
collectFiles()()
Python error:
Python exception: (2, 'No existe el archivo o el directorio', '/home/life/Escritorio/borrame/borramedos/Untitled_COLLECT/')
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/life/.Natron/Python_GUI/collectFiles/collectFiles.py", line 218, in collectFiles
    os.chdir(rootFolder)
OSError: (2, 'No existe el archivo o el directorio', '/home/life/Escritorio/borrame/borramedos/Untitled_COLLECT/')

**Comment by bonalex01dev** [comment]
AutoAlpha:
can't reproduce win10 natron 2.4.1

connectNodesList:
This script doesn't exist in the repo can you tell the exact script name? Maybe an older version deprecated of the community scripts ?

openLocation:
please test PR that is supposed to fix (for Linux distros that don't have thunar explorer

Render:
please update the path in the script to your actual player

collectFiles:
Did you setup the output folder in the script itself?

**Comment by tebicap** [comment]
thanks for answering, I see that pluggins has changed a lot since I opened the issue. I don't have that scripts anymore but I tested the new ones and still some of they are not working, and I do not setup the path well also. Could you give me an example please?  I tried adding this in the initGui.py file but don't work:

# Tools -> Channel
from '/here my home/.Natron/natron-python-scripting-master/'.Python_GUI.autoAlpha.autoAlpha import *

from '/here my home/.Natron/natron-python-scripting-master/'.autoAlpha.autoAlpha import *

from ('/here my home/.Natron/natron-python-scripting-master/').Python_GUI.autoAlpha.autoAlpha import *

etc.

by default initGui.py comes as following: from Python_GUI.autoAlpha.autoAlpha import *

**Comment by bonalex01dev** [comment]
I think path are relatives and thus should not be changed (can't check now)

**Comment by yt2w** [comment]
Hey! Not affiliated with the Natron project — just a community member who spent a while staring at Natron's embedded interpreter problem and ended up shipping something.
I put together natron-mcp: https://github.com/yt2w/natron-mcp
It's an MCP server that lets Claude (Desktop, Code, or any other MCP-capable client) drive a live Natron session directly — create and connect nodes, read/set parameters, manage projects, trigger renders, and drop into an arbitrary Python escape hatch when the typed tools don't cover what you need.
The trickier part under the hood: Natron embeds its own private Python interpreter (2.7 on older builds, 3.10 on current Windows ones), so you can't pip-install the MCP SDK into it. The solution is a two-layer split — a proper Python 3.10+ MCP server on one side, and a tiny dependency-free loopback TCP bridge running inside Natron on the other, marshaling everything through Natron's Qt main thread the way the API requires. Both embedded interpreter versions are supported.
Current tool count is 20 — node CRUD, wiring, param get/set, reader/writer helpers, project ops, render, and natron_run_script as a catch-all. Works on Windows, macOS, and Linux. MIT licensed, includes a pytest suite with a fake Natron API so tests run without Natron installed.
Happy to hear if something breaks or if there are ops that should be first-class tools. Issues and PRs welcome
